"""默认食材初始化数据 - 涵盖日常家庭烹饪常用食材。"""


DEFAULT_INGREDIENTS = [
    # ========== 畜肉类 ==========
    {"name": "猪肉", "aliases": ["生猪猪", "猪"]},
    {"name": "五花肉", "aliases": ["五花", "五花儿肉", "猪五花"]},
    {"name": "里脊肉", "aliases": ["里脊", "猪里脊", "梅条肉"]},
    {"name": "梅花肉", "aliases": ["梅花", "猪肩肉", "肩胛肉"]},
    {"name": "前腿肉", "aliases": ["前夹肉", "前臀尖"]},
    {"name": "后腿肉", "aliases": ["后臀尖", "坐板肉"]},
    {"name": "猪蹄", "aliases": ["猪手", "猪脚", "爪子"]},
    {"name": "猪肘", "aliases": ["肘子", "蹄髈", "前肘", "后肘"]},
    {"name": "排骨", "aliases": ["猪排", "猪肋排", "肋排", "子排"]},
    {"name": "筒骨", "aliases": ["大骨", "筒子骨", "棒骨", "猪筒骨"]},
    {"name": "筒子骨", "aliases": ["猪骨"]},
    {"name": "猪肝", "aliases": ["猪肝儿"]},
    {"name": "猪肚", "aliases": ["猪肚子", "肚仁"]},
    {"name": "猪大肠", "aliases": ["肥肠", "大肠"]},
    {"name": "猪小肠", "aliases": ["小肠", "生肠"]},
    {"name": "猪腰", "aliases": ["腰子", "猪肾"]},
    {"name": "猪心", "aliases": ["猪心儿"]},
    {"name": "猪舌", "aliases": ["猪舌头", "口条"]},
    {"name": "猪油", "aliases": ["猪板油", "板油", "荤油"]},
    {"name": "猪肉馅", "aliases": ["肉馅", "猪肉糜", "猪绞肉"]},
    {"name": "猪肉丝", "aliases": ["肉丝", "猪肉丝"]},
    {"name": "牛肉", "aliases": ["牛"]},
    {"name": "牛腩", "aliases": ["牛肚子", "牛肚腩"]},
    {"name": "牛里脊", "aliases": ["菲力", "牛柳", "里脊"]},
    {"name": "牛腱子", "aliases": ["腱子肉", "牛腱"]},
    {"name": "牛腱", "aliases": ["牛筋肉"]},
    {"name": "牛筋", "aliases": ["牛蹄筋"]},
    {"name": "牛肉馅", "aliases": ["牛肉糜", "牛绞肉"]},
    {"name": "牛百叶", "aliases": ["毛肚", "百叶", "千层肚"]},
    {"name": "牛舌", "aliases": ["牛口条", "牛舌头"]},
    {"name": "羊肉", "aliases": ["羊"]},
    {"name": "羊腿", "aliases": ["羊后腿", "羊前腿"]},
    {"name": "羊排", "aliases": ["羊肋排", "法式羊排"]},
    {"name": "羊肉卷", "aliases": ["涮羊肉", "冷冻羊肉片"]},
    {"name": "羊蝎子", "aliases": ["羊脊骨", "羊龙骨"]},

    # ========== 禽肉类 ==========
    {"name": "鸡肉", "aliases": ["鸡", "鸡子"]},
    {"name": "三黄鸡", "aliases": ["清远鸡", "走地鸡", "土鸡"]},
    {"name": "土鸡", "aliases": ["走地鸡", "笨鸡"]},
    {"name": "肉鸡", "aliases": ["白羽鸡", "速成鸡"]},
    {"name": "乌鸡", "aliases": ["乌骨鸡", "丝羽乌骨鸡"]},
    {"name": "老母鸡", "aliases": ["老鸡", "母鸡", "月子鸡"]},
    {"name": "公鸡", "aliases": ["雄鸡", "叫鸡"]},
    {"name": "童子鸡", "aliases": ["嫩鸡", "仔鸡"]},
    {"name": "鸡胸肉", "aliases": ["鸡胸", "鸡大胸", "鸡小胸"]},
    {"name": "鸡腿", "aliases": ["琵琶腿", "鸡大腿", "鸡小腿"]},
    {"name": "鸡翅", "aliases": ["鸡翅膀", "鸡翼", "翅中", "翅根"]},
    {"name": "凤爪", "aliases": ["鸡爪", "鸡脚", "鸡掌"]},
    {"name": "鸡胗", "aliases": ["鸡肫", "鸡胃", "内金"]},
    {"name": "鸡心", "aliases": ["鸡心儿"]},
    {"name": "鸡肝", "aliases": ["鸡肝儿"]},
    {"name": "鸡架", "aliases": ["鸡骨架", "鸡壳"]},
    {"name": "鸡全腿", "aliases": ["棒棒腿"]},
    {"name": "鸡肉馅", "aliases": ["鸡肉糜", "鸡绞肉"]},
    {"name": "鸭肉", "aliases": ["鸭", "鸭子"]},
    {"name": "鸭腿", "aliases": ["鸭大腿"]},
    {"name": "鸭胸", "aliases": ["鸭胸肉"]},
    {"name": "鸭翅", "aliases": ["鸭翅膀"]},
    {"name": "鸭掌", "aliases": ["鸭爪", "鸭蹼"]},
    {"name": "鸭血", "aliases": ["鸭血豆腐", "液体鸭血"]},
    {"name": "鹅肉", "aliases": ["鹅", "大鹅"]},
    {"name": "鸽肉", "aliases": ["鸽子", "乳鸽", "白鸽"]},
    {"name": "鹌鹑", "aliases": ["鹌鹑鸟"]},

    # ========== 肉制品/加工 ==========
    {"name": "火腿", "aliases": ["金华火腿", "云腿", "中方火腿"]},
    {"name": "金华火腿", "aliases": ["金腿", "南腿"]},
    {"name": "宣威火腿", "aliases": ["云腿", "宣腿"]},
    {"name": "腊肉", "aliases": ["烟熏肉", "腊味"]},
    {"name": "腊肠", "aliases": ["香肠", "广式腊肠", "川味腊肠"]},
    {"name": "培根", "alias": ["烟熏五花肉", "西式培根", "培根片"]},
    {"name": "火腿肠", "aliases": ["火腿肠儿", "午餐肉肠"]},
    {"name": "中式香肠", "aliases": ["腊味肠", "风干肠"]},
    {"name": "肉松", "aliases": ["猪肉松", "鸡肉松"]},
    {"name": "肉丸", "aliases": ["肉圆", "狮子头小", "水煮丸子"]},
    {"name": "午餐肉", "aliases": ["火腿肉", "罐头肉", "spam"]},
    {"name": "叉烧", "aliases": ["叉烧肉", "蜜汁叉烧"]},
    {"name": "肉干", "aliases": ["猪肉干", "猪肉脯"]},
    {"name": "咸肉", "aliases": ["腌制肉", "盐肉"]},
    {"name": "酱牛肉", "aliases": ["卤牛肉", "五香牛肉"]},
    {"name": "卤味", "aliases": ["卤菜", "卤货", "卤水"]},
    {"name": "牛羊肉干", "aliases": ["风干肉", "肉干"]},
    {"name": "白切鸡", "aliases": ["白斩鸡"]},
    {"name": "鸡胸", "aliases": ["水煮鸡胸"]},
    {"name": "鸡精", "aliases": ["鸡粉", "鲜味料"]},

    # ========== 水产-鱼类 ==========
    {"name": "草鱼", "aliases": ["鲩鱼", "草根", "混子"]},
    {"name": "鲫鱼", "aliases": ["鲫瓜子", "河鲫", "喜头鱼"]},
    {"name": "鲤鱼", "aliases": ["鲤拐子", "鲤子"]},
    {"name": "黑鱼", "aliases": ["乌鱼", "财鱼", "蛇头鱼", "生鱼"]},
    {"name": "鲈鱼", "aliases": ["花鲈", "海鲈", "河鲈"]},
    {"name": "罗非鱼", "aliases": ["非洲鲫鱼", "福寿鱼", "吴郭鱼"]},
    {"name": "鳜鱼", "aliases": ["桂花鱼", "季花鱼", "胖鳜"]},
    {"name": "鲶鱼", "aliases": ["土鲶", "鲇鱼", "胡子鲶"]},
    {"name": "昂刺鱼", "aliases": ["黄颡鱼", "嘎牙鱼", "黄姑子"]},
    {"name": "带鱼", "aliases": ["刀鱼", "裙带鱼", "海刀鱼"]},
    {"name": "鲳鱼", "aliases": ["平鱼", "银鲳", "昌鱼"]},
    {"name": "金枪鱼", "aliases": ["吞拿鱼", "鲔鱼", "海底鸡"]},
    {"name": "三文鱼", "aliases": ["鲑鱼", "撒蒙鱼", "大马哈"]},
    {"name": "鳕鱼", "aliases": ["狭鳕", "明太鱼", "大头鱼"]},
    {"name": "黄花鱼", "aliases": ["黄鱼", "黄瓜鱼", "大黄鱼", "小黄鱼"]},
    {"name": "鲅鱼", "aliases": ["马鲛鱼", "蓝点马鲛"]},
    {"name": "秋刀鱼", "aliases": ["竹刀鱼"]},
    {"name": "鳗鱼", "aliases": ["白鳝", "河鳗", "日本鳗"]},
    {"name": "多宝鱼", "aliases": ["大菱鲆", "欧洲比目鱼"]},
    {"name": "石斑鱼", "aliases": ["海石斑", "龙虎斑", "青斑"]},
    {"name": "沙丁鱼", "aliases": ["鰛鱼"]},
    {"name": "比目鱼", "aliases": ["鲽鱼", "偏口鱼", "大地鱼"]},
    {"name": "银鱼", "aliases": ["面条鱼", "银鱼干"]},
    {"name": "墨鱼", "aliases": ["乌贼", "目鱼", "墨斗鱼"]},
    {"name": "鱿鱼", "aliases": ["枪乌贼", "鱿鱼板"]},
    {"name": "章鱼", "aliases": ["八爪鱼", "小八梢鱼", "蛸"]},
    {"name": "多春鱼", "aliases": ["毛鳞鱼"]},
    {"name": "秋鲑", "aliases": ["大马哈鱼", "鲑鱼"]},
    {"name": "黄鳝", "aliases": ["鳝鱼", "长鱼"]},
    {"name": "泥鳅", "aliases": ["鳅鱼", "胡溜"]},
    {"name": "鱼丸", "aliases": ["鱼圆", "鱼旦", "水煮鱼丸"]},
    {"name": "鱼豆腐", "aliases": ["鱼板", "关东煮豆腐"]},
    {"name": "干鱼", "aliases": ["鱼干", "咸鱼", "晾鱼干"]},

    # ========== 水产-虾蟹贝壳 ==========
    {"name": "虾", "aliases": ["大虾", "对虾", "河虾"]},
    {"name": "基围虾", "aliases": ["沙虾", "麻虾", "虎虾"]},
    {"name": "草虾", "aliases": ["斑节虾", "鬼虾", "牛形对虾"]},
    {"name": "明虾", "aliases": ["对虾", "大明虾"]},
    {"name": "青虾", "aliases": ["河虾", "沼虾"]},
    {"name": "北极虾", "aliases": ["北极甜虾", "甜虾"]},
    {"name": "龙虾", "aliases": ["小龙虾", "淡水龙虾", "克氏原螯虾"]},
    {"name": "皮皮虾", "aliases": ["虾蛄", "濑尿虾", "爬虾"]},
    {"name": "虾仁", "aliases": ["虾肉", "海米", "鲜虾仁"]},
    {"name": "虾皮", "aliases": ["毛虾", "磷虾皮"]},
    {"name": "螃蟹", "aliases": ["大闸蟹", "河蟹"]},
    {"name": "梭子蟹", "aliases": ["白蟹", "花蟹"]},
    {"name": "花蟹", "aliases": ["远洋花蟹", "蓝花蟹"]},
    {"name": "青蟹", "aliases": ["红树林蟹", "膏蟹"]},
    {"name": "扇贝", "aliases": ["海扇", "干贝", "续随子"]},
    {"name": "干贝", "aliases": ["瑶柱", "马甲柱", "肉柱"]},
    {"name": "牡蛎", "aliases": ["生蚝", "海蛎子", "蚝"]},
    {"name": "生蚝", "aliases": ["海蛎", "青蚝"]},
    {"name": "鲍鱼", "aliases": ["明目鱼", "镜面鱼", "九孔"]},
    {"name": "八爪鱼", "aliases": ["章鱼", "小八梢鱼", "蛸"]},
    {"name": "蛤蜊", "aliases": ["花蛤", "沙蛤", "蛤仔"]},
    {"name": "花甲", "aliases": ["花蛤", "蛤蜊", "芒果螺"]},
    {"name": "淡菜", "aliases": ["海红", "壳菜", "贻贝"]},
    {"name": "蛏子", "aliases": ["蛏", "青子", "竹蛏"]},
    {"name": "蚬子", "aliases": ["黄蚬", "沙蚬", "蝲蜊"]},
    {"name": "田螺", "aliases": ["中国圆田螺", "螺蛳", "水螺"]},
    {"name": "螺", "aliases": ["海螺", "田螺", "海瓜子"]},
    {"name": "钉螺", "aliases": ["钉螺蛳"]},
    {"name": "海胆", "aliases": ["海刺猬", "刺锅子"]},
    {"name": "海参", "aliases": ["海鼠", "刺参", "沙噀"]},
    {"name": "海蜇", "aliases": ["水母", "海蜇头", "海蜇皮"]},

    # ========== 蛋类 ==========
    {"name": "鸡蛋", "aliases": ["鲜鸡蛋", "洋鸡蛋", "草鸡蛋"]},
    {"name": "草鸡蛋", "aliases": ["土鸡蛋", "笨鸡蛋", "走地鸡蛋"]},
    {"name": "鸭蛋", "aliases": ["鲜鸭蛋", "鸭卵子"]},
    {"name": "咸鸭蛋", "aliases": ["腌鸭蛋", "咸蛋黄"]},
    {"name": "皮蛋", "aliases": ["松花蛋", "松花", "溏心蛋"]},
    {"name": "鹌鹑蛋", "aliases": ["鹑鸟蛋", "鹌鹑蛋儿"]},
    {"name": "鸽蛋", "aliases": ["鸽子蛋"]},
    {"name": "鹅蛋", "aliases": ["豁鹅蛋"]},
    {"name": "鸡蛋黄", "aliases": ["蛋黄", "鸡蛋黄儿", "生蛋黄"]},
    {"name": "鸡蛋清", "aliases": ["蛋清", "蛋白", "鸡蛋清儿"]},
    {"name": "咸蛋黄", "aliases": ["油蛋黄", "月亮蛋黄"]},
    {"name": "蛋饺", "aliases": ["蛋饺儿", "蛋皮肉饺"]},

    # ========== 豆腐/豆制品 ==========
    {"name": "豆腐", "aliases": ["嫩豆腐", "老豆腐", "板豆腐"]},
    {"name": "老豆腐", "aliases": ["北豆腐", "卤水豆腐"]},
    {"name": "嫩豆腐", "aliases": ["南豆腐", "嫩脂豆腐", "绢豆腐"]},
    {"name": "内酯豆腐", "aliases": ["内脂豆腐", "盒装豆腐"]},
    {"name": "豆腐皮", "aliases": ["千张", "千张皮", "豆腐衣", "油皮"]},
    {"name": "腐竹", "aliases": ["支竹", "皮腐", "豆腐棍"]},
    {"name": "豆皮", "aliases": ["千张", "干豆腐"]},
    {"name": "百页", "aliases": ["千张", "千层"]},
    {"name": "百页结", "aliases": ["百叶结"]},
    {"name": "油豆腐", "aliases": ["豆泡", "豆腐果", "油炸豆腐"]},
    {"name": "素鸡", "aliases": ["卤豆腐卷", "豆腐卷"]},
    {"name": "干豆腐", "aliases": ["南豆腐皮", "干张"]},
    {"name": "豆干", "aliases": ["豆腐干", "香干"]},
    {"name": "豆腐乳", "aliases": ["腐乳", "酱豆腐"]},
    {"name": "豆汁", "aliases": ["豆浆", "白豆浆"]},
    {"name": "豆浆", "aliases": ["豆腐浆", "豆奶"]},
    {"name": "豆渣", "aliases": ["豆腐渣", "豆粨"]},
    {"name": "豆腐脑", "aliases": ["豆花", "老豆腐"]},
    {"name": "豆花", "aliases": ["豆腐脑", "腐脑"]},
    {"name": "粉丝", "aliases": ["淀粉丝", "粉条", "冬粉"]},
    {"name": "粉条", "aliases": ["宽粉", "红薯粉"]},
    {"name": "粉皮", "aliases": ["拉皮", "东北大拉皮"]},
    {"name": "面筋", "aliases": ["水面筋", "烤麸"]},
    {"name": "烤麸", "aliases": ["面筋泡", "熟面筋"]},
    {"name": "油面筋", "aliases": ["面筋泡", "油筋"]},
    {"name": "油豆皮", "aliases": ["豆腐皮", "油皮"]},

    # ========== 叶菜类 ==========
    {"name": "大白菜", "aliases": ["结球白菜", "包心白菜"]},
    {"name": "小白菜", "aliases": ["青菜", "油白菜", "上海青"]},
    {"name": "上海青", "aliases": ["小青菜", "苏州青", "汤匙菜"]},
    {"name": "油菜", "aliases": ["普通油菜", "野油菜"]},
    {"name": "菠菜", "aliases": ["波斯草", "赤根菜"]},
    {"name": "生菜", "aliases": ["叶用莴苣", "团生菜"]},
    {"name": "油麦菜", "aliases": ["莜麦菜", "尖叶莴苣"]},
    {"name": "空心菜", "aliases": ["蕹菜", "通菜", "竹叶菜"]},
    {"name": "茼蒿", "aliases": ["蓬蒿菜", "春菊", "菊花菜"]},
    {"name": "芥蓝", "aliases": ["芥兰", "绿叶甘蓝"]},
    {"name": "菜心", "aliases": ["菜薹", "广东菜心", "菜尖"]},
    {"name": "木耳菜", "aliases": ["落葵", "豆腐菜", "胭脂菜"]},
    {"name": "苋菜", "aliases": ["红苋", "白苋", "红菜"]},
    {"name": "茴香", "aliases": ["小茴香", "香丝菜"]},
    {"name": "芫荽", "aliases": ["香菜", "胡荽"]},
    {"name": "香菜", "aliases": ["芫荽", "满天星"]},
    {"name": "韭菜", "aliases": ["起阳草", "懒人菜"]},
    {"name": "韭黄", "aliases": ["黄韭", "韭菜黄"]},
    {"name": "蒜苗", "aliases": ["青蒜", "蒜薹"]},
    {"name": "蒜黄", "aliases": ["黄蒜苗"]},
    {"name": "小葱", "aliases": ["香葱", "细葱", "分葱"]},
    {"name": "大葱", "aliases": ["白葱", "青葱", "和事草"]},
    {"name": "洋葱", "aliases": ["圆葱", "球葱", "玉葱"]},
    {"name": "红葱", "aliases": ["红皮洋葱", "紫葱"]},
    {"name": "香葱", "aliases": ["多葱", "小葱", "北葱"]},
    {"name": "青江菜", "aliases": ["青梗菜"]},
    {"name": "甘蓝", "aliases": ["卷心菜", "包菜", "圆白菜"]},
    {"name": "包菜", "aliases": ["卷心菜", "圆白菜", "高丽菜"]},
    {"name": "紫甘蓝", "aliases": ["紫包菜", "红甘蓝"]},
    {"name": "羽衣甘蓝", "aliases": ["无头甘蓝"]},
    {"name": "芥菜", "aliases": ["腌菜", "辣菜"]},
    {"name": "雪里蕻", "aliases": ["雪菜", "排冬菜"]},
    {"name": "盖菜", "aliases": ["花芥菜"]},
    {"name": "菜花", "aliases": ["花菜", "花椰菜"]},
    {"name": "西兰花", "aliases": ["绿花菜", "青花菜"]},
    {"name": "芥蓝", "aliases": ["芥兰", "中国西兰花"]},
    {"name": "萝卜", "aliases": ["白萝卜", "菜头"]},
    {"name": "红萝卜", "aliases": ["胡萝卜", "红菜头"]},
    {"name": "胡萝卜", "aliases": ["红萝卜", "甘笋", "丁香萝卜"]},
    {"name": "青萝卜", "aliases": ["青头萝卜", "心里美"]},
    {"name": "水萝卜", "aliases": ["小红萝卜", "杨花萝卜"]},
    {"name": "芜菁", "aliases": ["蔓菁", "大头菜"]},
    {"name": "莴苣", "aliases": ["莴笋", "青笋"]},
    {"name": "莴笋", "aliases": ["莴苣笋", "香莴笋"]},
    {"name": "大头菜", "aliases": ["根芥菜", "冲菜"]},

    # ========== 茄果类 ==========
    {"name": "土豆", "aliases": ["马铃薯", "山药蛋", "洋芋"]},
    {"name": "红薯", "aliases": ["地瓜", "番薯", "山芋"]},
    {"name": "白薯", "aliases": ["甘薯", "地瓜"]},
    {"name": "紫薯", "aliases": ["紫心甘薯", "紫心番薯"]},
    {"name": "山药", "aliases": ["薯蓣", "淮山药", "怀山药"]},
    {"name": "芋头", "aliases": ["芋艿", "毛芋"]},
    {"name": "魔芋", "aliases": ["蒟蒻", "妖芋", "麻芋"]},
    {"name": "木薯", "aliases": ["树薯", "南洋薯"]},
    {"name": "莲藕", "aliases": ["藕", "莲菜", "荷藕"]},
    {"name": "藕", "aliases": ["莲菜", "莲藕"]},
    {"name": "马蹄", "aliases": ["荸荠", "地栗", "乌芋"]},
    {"name": "慈姑", "aliases": ["茨菰", "白地栗"]},
    {"name": "百合", "aliases": ["百合蒜", "夜合"]},
    {"name": "茄子", "aliases": ["茄瓜", "矮瓜", "吊菜"]},
    {"name": "辣椒", "aliases": ["海椒", "辣子"]},
    {"name": "青椒", "aliases": ["菜椒", "柿子椒", "甜椒"]},
    {"name": "尖椒", "aliases": ["朝天椒", "长柄椒"]},
    {"name": "彩椒", "aliases": ["彩色甜椒", "灯笼椒"]},
    {"name": "西红柿", "aliases": ["番茄", "洋柿子", "狼桃"]},
    {"name": "番茄", "aliases": ["西红柿", "小金瓜"]},
    {"name": "圣女果", "aliases": ["樱桃番茄", "小番茄", "小西红柿"]},
    {"name": "樱桃番茄", "aliases": ["小番茄", "圣女果"]},
    {"name": "黄瓜", "aliases": ["胡瓜", "青瓜", "刺瓜"]},
    {"name": "丝瓜", "aliases": ["水菜", "布瓜", "菜瓜"]},
    {"name": "苦瓜", "aliases": ["凉瓜", "半锦荔枝"]},
    {"name": "南瓜", "aliases": ["倭瓜", "老南瓜", "番瓜"]},
    {"name": "冬瓜", "aliases": ["枕瓜", "东瓜"]},
    {"name": "西葫芦", "aliases": ["茭瓜", "角瓜", "白瓜"]},
    {"name": "佛手瓜", "aliases": ["洋茄子", "合掌瓜"]},
    {"name": "瓠瓜", "aliases": ["扁蒲", "蒲瓜"]},
    {"name": "秋葵", "aliases": ["黄秋葵", "羊角豆", "补肾菜"]},
    {"name": "玉米", "aliases": ["苞谷", "苞米", "玉蜀黍"]},
    {"name": "甜玉米", "aliases": ["甜苞谷", "水果玉米"]},
    {"name": "糯玉米", "aliases": ["粘玉米", "蜡质玉米"]},
    {"name": "玉米笋", "aliases": ["小玉米", "玉米芯"]},
    {"name": "毛豆", "aliases": ["青豆", "枝青"]},

    # ========== 菌菇类 ==========
    {"name": "香菇", "aliases": ["花菇", "厚菇", "香蕈"]},
    {"name": "花菇", "aliases": ["香菇王", "菊花菇"]},
    {"name": "平菇", "aliases": ["侧耳", "糙皮侧耳", "青荤"]},
    {"name": "金针菇", "aliases": ["冬菇", "毛柄金钱菌", "增智菇"]},
    {"name": "杏鲍菇", "aliases": ["刺芹侧耳", "杏鲍"]},
    {"name": "口蘑", "aliases": ["白蘑菇", "蒙古口蘑"]},
    {"name": "草菇", "aliases": ["兰花菇", "中国菇"]},
    {"name": "猴头菇", "aliases": ["猴头", "猴头菌"]},
    {"name": "茶树菇", "aliases": ["茶薪柱状田头菇"]},
    {"name": "鸡腿菇", "aliases": ["毛头鬼伞", "白鸡腿菇"]},
    {"name": "竹荪", "aliases": ["竹笙", "网纱菌"]},
    {"name": "牛肝菌", "aliases": ["大脚菇"]},
    {"name": "鸡枞", "aliases": ["鸡枞菌", "把菇"]},
    {"name": "干巴菌", "aliases": ["干巴"]},
    {"name": "银耳", "aliases": ["白木耳", "雪耳"]},
    {"name": "黑木耳", "aliases": ["黑菜", "木蛾", "云耳"]},
    {"name": "白木耳", "aliases": ["银耳", "雪耳"]},
    {"name": "云耳", "aliases": ["黑木耳", "光木耳"]},
    {"name": "石耳", "aliases": ["岩耳"]},
    {"name": "姬松茸", "aliases": ["巴西蘑菇", "小松茸"]},
    {"name": "松茸", "aliases": ["松口蘑", "松菇"]},
    {"name": "榛蘑", "aliases": ["蜜环菌", "假蜜环菌"]},
    {"name": "鹿茸菌", "aliases": ["鹿角菌"]},
    {"name": "海鲜菇", "aliases": ["真姬菇", "蟹味菇"]},
    {"name": "蟹味菇", "aliases": ["真姬菇", "海鲜菇"]},
    {"name": "白玉菇", "aliases": ["白色蟹味菇"]},
    {"name": "松菇", "aliases": ["松蘑"]},

    # ========== 葱姜蒜 ==========
    {"name": "大蒜", "aliases": ["蒜头", "独头蒜", "胡蒜"]},
    {"name": "蒜头", "aliases": ["大蒜"]},
    {"name": "蒜薹", "aliases": ["蒜苔", "蒜苗"]},
    {"name": "蒜黄", "aliases": ["黄蒜苗"]},
    {"name": "生姜", "aliases": ["姜", "黄姜", "老姜"]},
    {"name": "姜", "aliases": ["生姜", "老姜"]},
    {"name": "老姜", "aliases": ["生姜", "姜母"]},
    {"name": "子姜", "aliases": ["嫩姜", "紫姜"]},
    {"name": "沙姜", "aliases": ["三奈", "山辣"]},
    {"name": "干姜", "aliases": ["白姜"]},
    {"name": "姜黄", "aliases": ["郁金", "黄姜"]},

    # ========== 调味香料 ==========
    {"name": "花椒", "aliases": ["川椒", "秦椒", "红椒"]},
    {"name": "麻椒", "aliases": ["青椒花椒"]},
    {"name": "藤椒", "aliases": ["竹叶花椒", "藤椒油原料"]},
    {"name": "八角", "aliases": ["大料", "大茴香", "八角茴香"]},
    {"name": "桂皮", "aliases": ["香桂", "柴桂", "官桂"]},
    {"name": "香叶", "aliases": ["月桂叶", "天竺叶"]},
    {"name": "荜拔", "aliases": ["鼠尾", "椹圣"]},
    {"name": "孜然", "aliases": ["枯野", "安息茴香"]},
    {"name": "白芷", "aliases": ["香白芷"]},
    {"name": "草果", "aliases": ["草果仁"]},
    {"name": "山奈", "aliases": ["沙姜", "三奈"]},
    {"name": "肉豆蔻", "aliases": ["玉果"]},
    {"name": "砂仁", "aliases": ["阳春砂"]},
    {"name": "公丁香", "aliases": ["丁子香"]},
    {"name": "母丁香", "aliases": ["鸡舌香"]},
    {"name": "甘松", "aliases": ["香甘松"]},
    {"name": "陈皮", "aliases": ["橘皮", "新会陈皮"]},
    {"name": "青皮", "aliases": ["青橘皮"]},
    {"name": "香橼", "aliases": ["香圆"]},
    {"name": "枳实", "aliases": ["枳壳"]},
    {"name": "山胡椒", "aliases": ["木香子", "见过的"]},
    {"name": "薄荷", "aliases": ["野薄荷", "夜息香"]},
    {"name": "紫苏", "aliases": ["白苏", "赤苏"]},
    {"name": "罗勒", "aliases": ["金不换", "九层塔"]},
    {"name": "迷迭香", "aliases": ["万年老"]},
    {"name": "百里香", "aliases": ["地椒"]},
    {"name": "莳萝", "aliases": ["洋茴香"]},
    {"name": "香茅", "aliases": ["柠檬草"]},
    {"name": "那必拉", "aliases": ["至必拉"]},
    {"name": "咖喱叶", "aliases": ["调料九里香"]},
    {"name": "罂粟籽", "aliases": ["御米", "粟子"]},
    {"name": "藏红花", "aliases": ["西红花", "番红花"]},
    {"name": "香草", "aliases": ["香子兰"]},

    # ========== 调味液体/油类 ==========
    {"name": "芝麻油", "aliases": ["香油", "麻油", "小磨香油"]},
    {"name": "花生油", "aliases": ["生油"]},
    {"name": "大豆油", "aliases": ["黄豆油", "色拉油"]},
    {"name": "菜籽油", "aliases": ["菜油", "芸薹油"]},
    {"name": "橄榄油", "aliases": ["原生橄榄油"]},
    {"name": "葵花籽油", "aliases": ["葵花油"]},
    {"name": "玉米油", "aliases": ["粟米油", "玉米胚芽油"]},
    {"name": "猪油", "aliases": ["大油", "荤油", "板油"]},
    {"name": "黄油", "aliases": ["白脱油", "乳脂"]},
    {"name": "椰子油", "aliases": ["椰油"]},
    {"name": "棕榈油", "aliases": ["棕油", "白棕榈油"]},
    {"name": "茶油", "aliases": ["野茶油", "山茶油"]},
    {"name": "葡萄籽油", "aliases": ["葡萄油"]},
    {"name": "亚麻籽油", "aliases": ["胡麻油", "亚麻油"]},
    {"name": "棉籽油", "aliases": ["棉子油"]},
    {"name": "稻米油", "aliases": ["米糠油"]},
    {"name": "辣椒油", "aliases": ["红油", "油辣子"]},
    {"name": "花椒油", "aliases": ["花椒仔油"]},
    {"name": "葱油", "aliases": ["葱油汁"]},
    {"name": "蚝油", "aliases": ["牡蛎油", "李锦记蚝油"]},
    {"name": "生抽", "aliases": ["鲜酱油", "酱青"]},
    {"name": "老抽", "aliases": ["红酱油", "酱油"]},
    {"name": "酱油", "aliases": ["黄酱", "普通酱油"]},
    {"name": "蒸鱼豉油", "aliases": ["蒸鱼酱油", "鱼汁"]},
    {"name": "料酒", "aliases": ["烹饪酒", "花雕", "老酒"]},
    {"name": "黄酒", "aliases": ["绍兴老酒", "绍兴酒", "加饭酒"]},
    {"name": "米醋", "aliases": ["白醋", "糖醋"]},
    {"name": "香醋", "aliases": ["镇江香醋", "老陈醋"]},
    {"name": "陈醋", "aliases": ["老陈醋", "山西陈醋"]},
    {"name": "白醋", "aliases": ["白米醋", "醋精"]},
    {"name": "醋", "aliases": ["米醋"]},
    {"name": "寿司醋", "aliases": ["寿司米醋"]},
    {"name": "柠檬汁", "aliases": ["柠檬水", "柠檬鲜汁"]},
    {"name": "椰浆", "aliases": ["椰奶", "椰汁"]},
    {"name": "椰浆粉", "aliases": ["厚椰乳"]},
    {"name": "淡奶", "aliases": ["奶水", "蒸发奶"]},
    {"name": "椰糖", "aliases": ["椰花糖"]},
    {"name": "糖浆", "aliases": ["糖水", "简单糖浆"]},
    {"name": "枫糖浆", "aliases": ["枫糖", "加拿大枫糖"]},
    {"name": "糖色", "aliases": ["焦糖色", "炒糖色"]},

    # ========== 调味品/酱类 ==========
    {"name": "食盐", "aliases": ["盐", "细盐", "精盐", "海盐"]},
    {"name": "盐", "aliases": ["食盐"]},
    {"name": "粗盐", "aliases": ["大粒盐", "久大盐"]},
    {"name": "海盐", "aliases": ["海水盐", "天日盐"]},
    {"name": "岩盐", "aliases": ["石盐"]},
    {"name": "低钠盐", "aliases": ["健康盐", "代盐"]},
    {"name": "白砂糖", "aliases": ["白糖", "细砂糖"]},
    {"name": "绵白糖", "aliases": ["细糖", "白绵糖"]},
    {"name": "红糖", "aliases": ["赤糖", "黑糖", "片糖"]},
    {"name": "冰糖", "aliases": ["大块冰糖", "单晶冰糖"]},
    {"name": "黑糖", "aliases": ["台湾黑糖", "冲绳黑糖"]},
    {"name": "麦芽糖", "aliases": ["饴糖", "水饴"]},
    {"name": "蜂蜜", "aliases": ["蜂糖", "食蜜", "蜜糖"]},
    {"name": "果葡糖浆", "aliases": ["高果糖浆"]},
    {"name": "淀粉", "aliases": ["生粉", "芡粉", "粉芡"]},
    {"name": "土豆淀粉", "aliases": ["太白粉", "马铃薯粉"]},
    {"name": "玉米淀粉", "aliases": ["生粉", "粟粉", "玉米粉"]},
    {"name": "豆粉", "aliases": ["大豆粉", "黄豆粉"]},
    {"name": "木薯淀粉", "aliases": ["泰国生粉", "菱粉"]},
    {"name": "红薯淀粉", "aliases": ["地瓜粉", "山芋粉"]},
    {"name": "绿豆淀粉", "aliases": ["绿豆粉"]},
    {"name": "澄粉", "aliases": ["澄面", "无筋面粉", "小麦淀粉"]},
    {"name": "糯米粉", "aliases": ["江米粉", "元霄粉"]},
    {"name": "粘米粉", "aliases": ["大米粉", "在来米粉"]},
    {"name": "低筋面粉", "aliases": ["低粉", "蛋糕粉"]},
    {"name": "中筋面粉", "aliases": ["中粉", "普通面粉"]},
    {"name": "高筋面粉", "aliases": ["高粉", "面包粉"]},
    {"name": "全麦面粉", "aliases": ["全麦粉"]},
    {"name": "自发粉", "aliases": ["自发中筋粉"]},
    {"name": "酵粉", "aliases": ["发酵粉", "发粉"]},
    {"name": "酵母", "aliases": ["面包酵母", "活性干酵母"]},
    {"name": "泡打粉", "aliases": ["发粉", "酥粉"]},
    {"name": "小苏打", "aliases": ["苏打粉", "食粉"]},
    {"name": "塔塔粉", "aliases": ["酸性剂"]},
    {"name": "碱粉", "aliases": ["碱面", "口碱"]},
    {"name": "明矾", "aliases": ["钾铝矾"]},
    {"name": "豆瓣酱", "aliases": ["郫县豆瓣", "蚕豆辣酱"]},
    {"name": "郫县豆瓣", "aliases": ["郫县豆瓣酱", "川酱"]},
    {"name": "黄豆酱", "aliases": ["黄酱", "大酱"]},
    {"name": "干黄酱", "aliases": ["面黄酱"]},
    {"name": "甜面酱", "aliases": ["甜酱"]},
    {"name": "大酱", "aliases": ["东北大酱", "盘酱"]},
    {"name": "味噌", "aliases": ["日式大酱"]},
    {"name": "韭花酱", "aliases": ["韭菜花"]},
    {"name": "芝麻酱", "aliases": ["麻酱", "芝麻糊"]},
    {"name": "花生酱", "aliases": ["花生糊"]},
    {"name": "番茄酱", "aliases": ["tomato ketchup"]},
    {"name": "番茄膏", "aliases": ["番茄糊", "浓缩番茄酱"]},
    {"name": "番茄沙司", "aliases": ["番茄调味酱"]},
    {"name": "沙茶酱", "aliases": ["沙茶", "沙爹酱"]},
    {"name": "柱侯酱", "aliases": ["柱候酱", "海鲜酱"]},
    {"name": "海鲜酱", "aliases": ["柱侯酱", "甜海鲜酱"]},
    {"name": "叉烧酱", "aliases": ["叉烧汁"]},
    {"name": "排骨酱", "aliases": ["排骨汁"]},
    {"name": "香辣酱", "aliases": ["辣酱", "辣椒酱"]},
    {"name": "辣椒酱", "aliases": ["辣酱", "老干妈"]},
    {"name": "油泼辣子", "aliases": ["油辣椒"]},
    {"name": "剁椒", "aliases": ["剁辣椒", "湖南剁椒"]},
    {"name": "糟辣椒", "aliases": ["糟辣子"]},
    {"name": "豆豉", "aliases": ["干豆豉", "香豉"]},
    {"name": "腊八豆", "aliases": ["腊豆"]},
    {"name": "黄灯笼辣椒酱", "aliases": ["黄灯笼辣酱"]},
    {"name": "甜辣酱", "aliases": ["泰式甜辣酱"]},
    {"name": "辣根", "aliases": ["马萝卜", "山葵"]},
    {"name": "山葵", "aliases": ["青芥辣"]},
    {"name": "芥末", "aliases": ["芥末酱", "wasabi"]},
    {"name": "胡椒粉", "aliases": ["黑胡椒粉", "白胡椒粉"]},
    {"name": "白胡椒粉", "aliases": ["白胡椒"]},
    {"name": "黑胡椒粉", "aliases": ["黑胡椒", "黑椒粉"]},
    {"name": "咖喱粉", "aliases": ["咖喱"]},
    {"name": "咖喱块", "aliases": ["日式咖喱", "咖喱酱"]},
    {"name": "五香粉", "aliases": ["五料粉"]},
    {"name": "十三香", "aliases": ["十全香"]},
    {"name": "七味唐辛子", "aliases": ["七味粉"]},
    {"name": "味精", "aliases": ["谷氨酸钠", "味素"]},
    {"name": "糖精", "aliases": ["糖精钠"]},
    {"name": "甜菊糖", "aliases": ["甜菊"]},
    {"name": "木糖醇", "aliases": ["戊五醇"]},
    {"name": "安赛蜜", "aliases": ["AK糖"]},
    {"name": "甜蜜素", "aliases": ["环己基氨基磺酸钠"]},
    {"name": "鸡精", "aliases": ["鸡粉", "鲜味宝"]},
    {"name": "蘑菇精", "aliases": ["菌菇精"]},
    {"name": "高汤", "aliases": ["鲜汤", "上汤"]},
    {"name": "高汤块", "aliases": ["浓汤宝", "汤块"]},
    {"name": "肉宝王", "aliases": ["增味剂"]},
    {"name": "红曲粉", "aliases": ["红曲米"]},
    {"name": "蛋黄酱", "aliases": ["mayo", "美乃滋"]},
    {"name": "千岛酱", "aliases": ["塔塔酱"]},
    {"name": "塔塔酱", "aliases": ["tartar sauce", "鱼肉酱"]},
    {"name": "意大利酱", "aliases": ["意粉酱", "红酱"]},
    {"name": "青酱", "aliases": ["pesto"]},
    {"name": "黑胡椒酱", "aliases": ["黑椒汁"]},
    {"name": "洋葱圈", "aliases": ["洋葱圈儿"]},

    # ========== 干货类 ==========
    {"name": "粉丝", "aliases": ["冬粉", "粉条", "细粉"]},
    {"name": "粉条", "aliases": ["宽粉", "红薯粉"]},
    {"name": "腐竹", "aliases": ["支竹", "腐皮"]},
    {"name": "干香菇", "aliases": ["干香"]},
    {"name": "干木耳", "aliases": ["黑木耳干"]},
    {"name": "干贝", "aliases": ["瑶柱", "马甲柱"]},
    {"name": "鱿鱼干", "aliases": ["鱿鱼", "干鱿鱼"]},
    {"name": "墨鱼干", "aliases": ["墨斗鱼干"]},
    {"name": "虾皮", "aliases": ["毛虾皮"]},
    {"name": "虾干", "aliases": ["海米", "虾米"]},
    {"name": "海米", "aliases": ["金钩", "开洋"]},
    {"name": "海带", "aliases": ["海带丝", "裙带菜干"]},
    {"name": "紫菜", "aliases": ["海苔", "条斑紫菜"]},
    {"name": "海苔", "aliases": ["条斑紫菜"]},
    {"name": "裙带菜", "aliases": ["海芥菜"]},
    {"name": "鱼胶", "aliases": ["花胶", "鱼肚"]},
    {"name": "干海参", "aliases": ["干刺参"]},
    {"name": "干鲍", "aliases": ["干鲍鱼"]},
    {"name": "墨鱼", "aliases": ["乌贼"]},
    {"name": "鱼翅", "aliases": ["鲨鱼鳍"]},
    {"name": "燕窝", "aliases": ["燕盏", "燕条"]},
    {"name": "雪蛤", "aliases": ["林蛙油", "蛤蟆油"]},
    {"name": "虫草花", "aliases": ["北虫草", "人工虫草"]},
    {"name": "羊肚菌", "aliases": ["干羊肚菌"]},
    {"name": "茶树菇干", "aliases": ["干茶树菇"]},
    {"name": "竹荪干", "aliases": ["干竹荪", "竹笙干"]},
    {"name": "干巴菌", "aliases": ["干巴"]},
    {"name": "干黄花菜", "aliases": ["黄花菜干", "金针菜干"]},
    {"name": "黄花菜", "aliases": ["金针菜", "忘忧草"]},
    {"name": "蕨菜", "aliases": ["龙头菜", "拳头菜"]},
    {"name": "发菜", "aliases": ["发状念珠藻"]},
    {"name": "地软", "aliases": ["地木耳", "地皮菜"]},
    {"name": "葛根", "aliases": ["葛"]},
    {"name": "薤白", "aliases": ["小根蒜"]},
    {"name": "白背木耳", "aliases": ["毛木耳"]},
    {"name": "红枣", "aliases": ["大枣", "干枣"]},
    {"name": "黑枣", "aliases": ["乌枣", "熏枣"]},
    {"name": "蜜枣", "aliases": ["甜点枣"]},
    {"name": "椰枣", "aliases": ["海枣"]},
    {"name": "枸杞", "aliases": ["宁夏枸杞", "红耳坠"]},
    {"name": "枸杞子", "aliases": ["甘枸杞"]},
    {"name": "桂圆", "aliases": ["龙眼"]},
    {"name": "干桂圆", "aliases": ["干龙眼", "龙眼肉"]},
    {"name": "莲子", "alias": ["莲蓬子", "莲肉"]},
    {"name": "莲子心", "aliases": ["莲薏", "莲心"]},
    {"name": "百合干", "aliases": ["干百合", "药百合"]},
    {"name": "薏米", "aliases": ["薏苡仁", "六谷米"]},
    {"name": "芡实", "aliases": ["鸡头米", "刺莲蓬实"]},
    {"name": "淮山", "aliases": ["淮山药", "怀山药"]},
    {"name": "葛粉", "aliases": ["葛根粉"]},
    {"name": "藕粉", "aliases": ["莲藕淀粉"]},
    {"name": "干莲子", "aliases": ["莲子干"]},
    {"name": "干百合", "aliases": ["百合干"]},
    {"name": "莲子干", "aliases": ["干莲子"]},
    {"name": "苦荞茶", "aliases": ["苦荞麦"]},
    {"name": "荞麦", "aliases": ["甜荞"]},
    {"name": "燕麦", "aliases": ["燕麦片", "莜麦"]},
    {"name": "藜麦", "aliases": ["印第安麦"]},
    {"name": "薏苡仁", "aliases": ["薏米", "苡米"]},
    {"name": "米粉", "aliases": ["大米粉"]},
    {"name": "糯米", "aliases": ["江米"]},
    {"name": "黑米", "aliases": ["紫米", "墨米"]},
    {"name": "糙米", "aliases": ["玄米"]},
    {"name": "小米", "aliases": ["粟米", "谷子"]},
    {"name": "大黄米", "aliases": ["糜子", "黍米"]},
    {"name": "高粱米", "aliases": ["蜀黍"]},
    {"name": "玉米", "aliases": ["苞谷", "苞米"]},
    {"name": "大米", "aliases": ["稻米", "白米"]},
    {"name": "泰国香米", "aliases": ["茉莉香米"]},
    {"name": "寿司米", "aliases": ["日本米"]},
    {"name": "藜麦", "aliases": ["昆诺阿藜"]},
    {"name": "西米", "aliases": ["西谷米"]},
    {"name": "荞麦面", "aliases": ["荞面"]},
    {"name": "拉面", "aliases": ["手拉面"]},
    {"name": "碱面", "aliases": ["切面", "挂面"]},
    {"name": "挂面", "aliases": ["干面条"]},
    {"name": "切面", "aliases": ["鲜面条", "手擀面"]},
    {"name": "手擀面", "aliases": ["手擀面条"]},
    {"name": "方便面", "aliases": ["泡面", "速食面"]},
    {"name": "河粉", "aliases": ["沙河粉"]},
    {"name": "肠粉", "aliases": ["拉肠", "布拉肠"]},
    {"name": "粉丝", "aliases": ["冬粉"]},
    {"name": "米线", "aliases": ["米粉"]},
    {"name": "米线干", "aliases": ["干米线"]},
    {"name": "薯粉", "aliases": ["红薯粉条"]},
    {"name": "腐竹", "aliases": ["支竹"]},
    {"name": "烤麸", "aliases": ["熟面筋"]},
    {"name": "年糕", "aliases": ["糍粑"]},
    {"name": "糍粑", "aliases": ["年糕块"]},
    {"name": "包子", "aliases": ["馒头", "鲜肉包"]},
    {"name": "饺子皮", "aliases": ["水饺皮"]},
    {"name": "馄饨皮", "aliases": ["云吞皮", "吞皮"]},
    {"name": "春卷皮", "aliases": ["薄饼皮"]},
    {"name": "烧麦皮", "aliases": ["卖皮"]},

    # ========== 坚果/果干 ==========
    {"name": "花生", "aliases": ["落花生", "地豆", "长生果"]},
    {"name": "花生油", "aliases": ["生油"]},
    {"name": "核桃", "aliases": ["胡桃", "英国核桃"]},
    {"name": "核桃仁", "aliases": ["核桃肉"]},
    {"name": "杏仁", "aliases": ["甜杏仁", "美国大杏仁"]},
    {"name": "扁桃仁", "aliases": ["巴旦木", "美国大杏仁"]},
    {"name": "腰果", "aliases": ["树花生"]},
    {"name": "碧根果", "aliases": ["长寿果", "美国山核桃"]},
    {"name": "夏威夷果", "aliases": ["澳洲坚果", "昆士兰栗"]},
    {"name": "开心果", "aliases": ["绿仁果"]},
    {"name": "松子", "aliases": ["红松籽", "开口松子"]},
    {"name": "榛子", "aliases": ["尖栗", "平榛"]},
    {"name": "板栗", "aliases": ["栗子", "毛栗", "风栗"]},
    {"name": "白果", "aliases": ["银杏", "公孙树子"]},
    {"name": "南瓜子", "aliases": ["白瓜子", "南瓜籽"]},
    {"name": "西瓜子", "aliases": ["黑瓜子"]},
    {"name": "葵花籽", "aliases": ["向日葵籽", "天葵子"]},
    {"name": "芝麻", "aliases": ["脂麻", "黑芝麻", "白芝麻"]},
    {"name": "黑芝麻", "aliases": ["胡脂麻", "黑脂麻"]},
    {"name": "白芝麻", "aliases": ["白脂麻"]},
    {"name": "亚麻籽", "aliases": ["胡麻籽", "亚麻仁"]},
    {"name": "奇亚籽", "aliases": ["奇异籽"]},
    {"name": "紫苏子", "aliases": ["苏籽", "黑苏子"]},
    {"name": "火麻仁", "aliases": ["麻子仁"]},

    # ========== 水果 ==========
    {"name": "苹果", "aliases": ["平安果", "蛇果", "红富士"]},
    {"name": "梨", "aliases": ["雪梨", "鸭梨", "香梨"]},
    {"name": "香蕉", "aliases": ["弓蕉", "大香蕉"]},
    {"name": "橙子", "aliases": ["甜橙", "广柑", "雪橙", "柳橙"]},
    {"name": "橘子", "aliases": ["桔子", "柑橘"]},
    {"name": "柠檬", "aliases": ["柠果", "洋柠檬"]},
    {"name": "葡萄", "aliases": ["提子", "草龙珠"]},
    {"name": "提子", "aliases": ["美国提子"]},
    {"name": "西瓜", "aliases": ["寒瓜", "夏瓜", "水瓜"]},
    {"name": "哈密瓜", "aliases": ["甜瓜", "网纹瓜"]},
    {"name": "甜瓜", "aliases": ["香瓜", "梨瓜"]},
    {"name": "草莓", "aliases": ["凤梨草莓", "洋莓"]},
    {"name": "蓝莓", "aliases": ["越橘", "都柿"]},
    {"name": "猕猴桃", "aliases": ["奇异果", "狐狸桃"]},
    {"name": "芒果", "aliases": ["蜜望", "檬果"]},
    {"name": "菠萝", "aliases": ["凤梨", "旺梨"]},
    {"name": "榴莲", "aliases": ["金枕头", "猫山王"]},
    {"name": "椰子", "aliases": ["可可椰子"]},
    {"name": "木瓜", "aliases": ["番木瓜", "万寿果"]},
    {"name": "火龙果", "aliases": ["红龙果", "仙人掌果"]},
    {"name": "百香果", "aliases": ["鸡蛋果", "热情果"]},
    {"name": "柚子", "aliases": ["文旦", "香抛", "霜柚"]},
    {"name": "桃子", "aliases": ["水蜜桃", "蟠桃", "毛桃"]},
    {"name": "李子", "aliases": ["布朗", "嘉庆子"]},
    {"name": "樱桃", "aliases": ["车厘子", "莺桃"]},
    {"name": "杨梅", "aliases": ["山杨梅", "朱红"]},
    {"name": "石榴", "aliases": ["安石榴", "丹若"]},
    {"name": "柿子", "aliases": ["红柿", "大盖柿"]},
    {"name": "枣", "aliases": ["红枣", "黑枣", "金丝蜜枣"]},
    {"name": "荔枝", "aliases": ["丹荔", "离枝"]},
    {"name": "龙眼", "aliases": ["桂圆", "益智"]},
    {"name": "枇杷", "aliases": ["芦橘", "金丸"]},
    {"name": "杨桃", "aliases": ["五敛子", "洋桃"]},
    {"name": "莲雾", "aliases": ["洋蒲桃", "爪哇蒲桃"]},
    {"name": "山竹", "aliases": ["莽吉柿", "山竹子"]},
    {"name": "圣女果", "aliases": ["小番茄"]},
    {"name": "无花果", "aliases": ["映日果", "蜜果"]},
    {"name": "桑葚", "aliases": ["桑果", "桑枣"]},
    {"name": "沙棘", "aliases": ["酸刺", "醋柳"]},
    {"name": "蔓越莓", "aliases": ["小红莓"]},
    {"name": "覆盆子", "aliases": ["树莓", "马林果"]},
    {"name": "黑莓", "aliases": ["黑布仑"]},

    # ========== 饮品/冲调 ==========
    {"name": "茶叶", "aliases": ["茶", "绿茶", "红茶", "乌龙茶"]},
    {"name": "绿茶", "aliases": ["龙井", "碧螺春", "毛尖"]},
    {"name": "红茶", "aliases": ["祁红", "滇红", "英红"]},
    {"name": "乌龙茶", "aliases": ["青茶", "铁观音", "大红袍"]},
    {"name": "普洱茶", "aliases": ["普茶", "古树茶"]},
    {"name": "菊花", "aliases": ["杭白菊", "胎菊"]},
    {"name": "茉莉花", "aliases": ["茉莉", "末丽"]},
    {"name": "玫瑰花", "aliases": ["徘徊花", "刺玫"]},
    {"name": "柠檬片", "aliases": ["柠檬干"]},
    {"name": "咖啡", "aliases": ["咖啡豆", "速溶咖啡"]},
    {"name": "可可粉", "aliases": ["可可"]},
    {"name": "抹茶粉", "aliases": ["抹茶"]},
    {"name": "椰汁", "aliases": ["椰子汁", "椰子水"]},
    {"name": "酸奶", "aliases": ["酸乳"]},
    {"name": "牛奶", "aliases": ["鲜牛奶", "纯牛奶"]},
    {"name": "羊奶", "aliases": ["山羊奶"]},
    {"name": "奶酪", "aliases": ["芝士", "起司"]},
    {"name": "芝士", "aliases": ["奶酪", "起司"]},
    {"name": "奶粉", "aliases": ["牛奶粉", "羊奶粉"]},
    {"name": "冰淇淋", "aliases": ["雪糕", "甜筒"]},
    {"name": "麦片", "aliases": ["谷物早餐", "即食麦片"]},
    {"name": "芝麻糊", "aliases": ["黑芝麻糊"]},

    # ========== 主食/煲汤 ==========
    {"name": "米饭", "aliases": ["白饭", "精白米饭"]},
    {"name": "稀饭", "aliases": ["粥", "白粥", "小米粥"]},
    {"name": "馒头", "aliases": ["蒸馍", "馍馍"]},
    {"name": "花卷", "aliases": ["卷子"]},
    {"name": "包子", "aliases": ["菜包", "肉包", "大肉包"]},
    {"name": "粽子", "aliases": ["角黍", "端午粽"]},
    {"name": "饺子", "aliases": ["水饺", "蒸饺"]},
    {"name": "馄饨", "aliases": ["云吞", "抄手", "扁食"]},
    {"name": "汤圆", "aliases": ["元宵"]},
    {"name": "青团", "aliases": ["艾草青团"]},
    {"name": "麻花", "aliases": ["油炸麻花"]},
    {"name": "油条", "aliases": ["油炸鬼", "油馍"]},
    {"name": "煎饼", "aliases": ["山东煎饼", "煎饼果子"]},
    {"name": "锅贴", "aliases": ["煎饺"]},
    {"name": "烧饼", "aliases": ["火烧", "烤饼"]},
    {"name": "肉夹馍", "aliases": ["腊汁肉夹馍"]},
    {"name": "凉皮", "aliases": ["酿皮"]},
    {"name": "蛋炒饭", "aliases": ["黄金炒饭"]},
    {"name": "炒面", "aliases": ["炒面条", "炒拉面"]},
    {"name": "拌面", "aliases": ["干拌面"]},
    {"name": "拉面", "aliases": ["牛肉面", "素面"]},
    {"name": "米线", "aliases": ["过桥米线", "酸辣粉"]},
    {"name": "螺蛳粉", "aliases": ["臭粉", "螺蛳米粉"]},
    {"name": "粉丝汤", "aliases": ["酸辣粉丝"]},
    {"name": "火锅", "aliases": ["火锅汤底"]},
    {"name": "麻辣烫", "aliases": ["麻辣串"]},
    {"name": "麻辣香锅", "aliases": ["香锅"]},
    {"name": "卤煮", "aliases": ["卤煮火烧"]},
    {"name": "羊汤", "aliases": ["羊肉汤", "羊杂汤"]},
    {"name": "骨头汤", "aliases": ["排骨汤", "筒骨汤"]},
    {"name": "鸡汤", "aliases": ["老母鸡汤", "清炖鸡"]},
    {"name": "粥", "aliases": ["稀饭", "白粥"]},
    {"name": "八宝粥", "aliases": ["腊八粥", "八宝饭"]},
    {"name": "银耳汤", "aliases": ["银耳羹"]},
    {"name": "羹", "aliases": ["汤羹", "浓羹"]},
    {"name": "汤", "aliases": ["高汤", "鲜汤"]}
]


def seed_ingredients(conn, now=None):
    """初始化默认食材数据到数据库。"""
    import secrets
    import time as _time
    if now is None:
        now = int(_time.time())

    inserted = 0
    skipped = 0
    for item in DEFAULT_INGREDIENTS:
        name = item["name"].strip()
        if not name:
            continue
        existing = conn.execute(
            "SELECT id FROM ingredient_canonical WHERE name = ?", (name,)
        ).fetchone()
        if existing:
            skipped += 1
            continue
        canonical_id = secrets.token_hex(8)
        conn.execute(
            "INSERT INTO ingredient_canonical(id, name, created_at) VALUES(?,?,?)",
            (canonical_id, name, now),
        )
        for alias in item.get("aliases", []):
            alias = alias.strip()
            if not alias or alias == name:
                continue
            conn.execute(
                "INSERT OR IGNORE INTO ingredient_aliases(id, canonical_id, alias, created_at) VALUES(?,?,?,?)",
                (secrets.token_hex(8), canonical_id, alias, now),
            )
        inserted += 1
    return {"inserted": inserted, "skipped": skipped, "total": len(DEFAULT_INGREDIENTS)}

