import {mkdirSync, writeFileSync} from 'fs';
import {join} from 'path';
import {SourceConfig} from './types';
import {fetch, readLocal} from './lib/fetcher';
import {getConverter} from './converters';
import {loadSources} from './sources/loader';

async function processSource(source: SourceConfig): Promise<string[]> {
  const converter = getConverter(source.converter);
  let raw: string;

  if (source.url) {
    console.log(`Fetching ${source.name} from ${source.url}`);
    raw = await fetch(source.url);
  } else if (source.path) {
    console.log(`Reading ${source.name} from ${source.path}`);
    raw = readLocal(source.path);
  } else {
    throw new Error(`Source ${source.name} has no url or path`);
  }

  const lines = raw.split('\n');
  const rules = converter.convert(lines);
  console.log(`  Converted ${rules.length} rules from ${source.name}`);
  return rules;
}

async function writeOutput(
  rules: string[],
  outputDir: string,
  filename: string,
  sourceName: string
): Promise<void> {
  mkdirSync(outputDir, { recursive: true });

  const header = [
    '! Auto-generated by cowjiang-adguard, do not edit manually',
    `! Source: ${sourceName}`,
    ''
  ].join('\n');

  const content = header + rules.join('\n') + '\n';
  const outPath = join(outputDir, filename);
  writeFileSync(outPath, content);
  console.log(`  Written ${rules.length} rules to ${outPath}`);
}

async function build(): Promise<void> {
  console.log('Starting rule conversion...\n');

  // Load all sources
  const sources = loadSources('sources');
  console.log(`Loaded ${sources.length} sources\n`);

  // Process each source separately (keeping original behavior)
  for (const source of sources) {
    const rules = await processSource(source);
    await writeOutput(rules, 'agrules', source.output, source.name);
    console.log('');
  }

  console.log('Build complete!');
}

build().catch(err => {
  console.error('Build failed:', err);
  process.exit(1);
});
